#ifndef _FACEPPAPI_H_
#define _FACEPPAPI_H_


typedef struct {
    int top, bottom, left, right;
} FACEPP_RECT;

typedef struct {
    int x, y;
} FACEPP_POINT;

typedef enum {
    CONTOUR_CHIN = 0,
    CONTOUR_LEFT1,
    CONTOUR_LEFT2,
    CONTOUR_LEFT4,
    CONTOUR_LEFT6,
    CONTOUR_LEFT8,
    CONTOUR_RIGHT1,
    CONTOUR_RIGHT2,
    CONTOUR_RIGHT4,
    CONTOUR_RIGHT6,
    CONTOUR_RIGHT8,
    LEFT_EYE_BOTTOM,
    LEFT_EYE_LEFT_CORNER,
    LEFT_EYE_PUPIL,
    LEFT_EYE_RIGHT_CORNER,
    LEFT_EYE_TOP,
    LEFT_EYEBROW_LEFT_CORNER,
    LEFT_EYEBROW_LOWER_MIDDLE,
    LEFT_EYEBROW_RIGHT_CORNER,
    LEFT_EYEBROW_UPPER_MIDDLE,
    MOUTH_LEFT_CORNER,
    MOUTH_LOWER_LIP_BOTTOM,
    MOUTH_LOWER_LIP_TOP,
    MOUTH_RIGHT_CORNER,
    MOUTH_UPPER_LIP_BOTTOM,
    MOUTH_UPPER_LIP_TOP,
    NOSE_CONTOUR_LOWER_MIDDLE,
    NOSE_LEFT,
    NOSE_RIGHT,
    NOSE_TIP,
    RIGHT_EYE_BOTTOM,
    RIGHT_EYE_LEFT_CORNER,
    RIGHT_EYE_PUPIL,
    RIGHT_EYE_RIGHT_CORNER,
    RIGHT_EYE_TOP,
    RIGHT_EYEBROW_LEFT_CORNER,
    RIGHT_EYEBROW_LOWER_MIDDLE,
    RIGHT_EYEBROW_RIGHT_CORNER,
    RIGHT_EYEBROW_UPPER_MIDDLE,
    LANDMARK_COUNT
} FACEPP_LANDMARK;


#define MT_LANDMARK_TOTAL   83


typedef struct {
    FACEPP_RECT rFace;// face position in a rectangle
    FACEPP_POINT landmarks[MT_LANDMARK_TOTAL];
} FACEPP_FACEINFO;



#endif //_FACEPPAPI_H_
